import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import 'react-phone-number-input/style.css'; // must come first
import "./globals.css";
import Navbar from "@/components/layout/Navbar";
import { Toaster } from "react-hot-toast";
import { Providers } from "./provider";
import Footer from "../components/layout/Footer";
import Script from "next/script";
import { GoogleOAuthProvider } from '@react-oauth/google';

const nunito = Nunito({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-nunito",
});

export const metadata: Metadata = {
  title: "Trip Swift",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <Script
          src="https://checkout.razorpay.com/v1/checkout.js"
          strategy="lazyOnload"
        />
      </head>
      <body className={nunito.className}>
        <Providers>
          <Navbar />
          {children}
          <Footer />
          <Toaster position="top-right" />
        </Providers>
      </body>
    </html>
  );
}